### PR TITLE
update eciSM966 based on v1.0.0

### PR DESCRIPTION
**Pull request by automator-metatlas**
MATLAB is selecting SOFTWARE OPENGL rendering.

                            < M A T L A B (R) >
                  Copyright 1984-2018 The MathWorks, Inc.
                   R2018b (9.5.0.944444) 64-bit (glnxa64)
                              August 28, 2018

 
To get started, type doc.
For product information, visit www.mathworks.com.
 

      _____   _____   _____   _____     _____     |
     /  ___| /  _  \ |  _  \ |  _  \   / ___ \    |   COnstraint-Based Reconstruction and Analysis
     | |     | | | | | |_| | | |_| |  | |___| |   |   The COBRA Toolbox - 2021
     | |     | | | | |  _  { |  _  /  |  ___  |   |
     | |___  | |_| | | |_| | | | \ \  | |   | |   |   Documentation:
     \_____| \_____/ |_____/ |_|  \_\ |_|   |_|   |   http://opencobra.github.io/cobratoolbox
                                                  | 

 > Checking if git is installed ...  Done (version: 1.8.3.).
 > Checking if the repository is tracked using git ...  Done.
 > Checking if curl is installed ...  Done.
 > Checking if remote can be reached ...  Done.
 > Initializing and updating submodules (this may take a while)... Done.
 > Adding all the files of The COBRA Toolbox ...  Done.
 > Define CB map output... set to svg.
 > TranslateSBML is installed and working properly.
 > Configuring solver environment variables ...
   - [----] ILOG_CPLEX_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   - [----] GUROBI_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   - [----] TOMLAB_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   - [----] MOSEK_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   Done.
 > Checking available solvers and solver interfaces ... Done.
 > Setting default solvers ... Done.
 > Saving the MATLAB path ... Done.
   - The MATLAB path was saved as ~/pathdef.m.

 > Summary of available solvers and solver interfaces

			Support 	   LP 	 MILP 	   QP 	 MIQP 	  NLP
	----------------------------------------------------------------------
	gurobi       	active        	    1 	    1 	    1 	    1 	    -
	ibm_cplex    	active        	    0 	    0 	    0 	    0 	    -
	tomlab_cplex 	active        	    0 	    0 	    0 	    0 	    -
	glpk         	active        	    1 	    1 	    - 	    - 	    -
	mosek        	active        	    0 	    - 	    0 	    - 	    -
	matlab       	active        	    0 	    - 	    - 	    - 	    0
	pdco         	active        	    1 	    - 	    1 	    - 	    -
	quadMinos    	active        	    1 	    - 	    - 	    - 	    -
	dqqMinos     	active        	    1 	    - 	    1 	    - 	    -
	cplex_direct 	active        	    0 	    0 	    0 	    - 	    -
	cplexlp      	active        	    0 	    - 	    - 	    - 	    -
	qpng         	passive       	    - 	    - 	    1 	    - 	    -
	tomlab_snopt 	passive       	    - 	    - 	    - 	    - 	    0
	lp_solve     	legacy        	    1 	    - 	    - 	    - 	    -
	----------------------------------------------------------------------
	Total        	-             	    6 	    2 	    4 	    1 	    0

 + Legend: - = not applicable, 0 = solver not compatible or not installed, 1 = solver installed.

 > You can solve LP problems using: 'gurobi' - 'glpk' - 'pdco' - 'quadMinos' 
 > You can solve MILP problems using: 'gurobi' - 'glpk' 
 > You can solve QP problems using: 'gurobi' - 'pdco' 
 > You can solve MIQP problems using: 'gurobi' 
 > You can solve NLP problems using: 

 > Checking for available updates ...
> You cannot update your fork using updateCobraToolbox() because this is a development branch.
> The current branch is: detached HEAD
> The last commit to the current branch is: 6c49aa
> You can use MATLAB.devTools (https://github.com/opencobra/MATLAB.devTools) to update your fork.
Converting COBRA structure to RAVEN..
Getting enzyme codes: Ready with rxn 100
Getting enzyme codes: Ready with rxn 200
Getting enzyme codes: Ready with rxn 300
Getting enzyme codes: Ready with rxn 400
Getting enzyme codes: Ready with rxn 500
Getting enzyme codes: Ready with rxn 600
Getting enzyme codes: Ready with rxn 700
Getting enzyme codes: Ready with rxn 800
Getting enzyme codes: Ready with rxn 900
Getting enzyme codes: Ready with rxn 1000
Getting enzyme codes: Ready with rxn 1100
Getting enzyme codes: Ready with rxn 1200
Getting enzyme codes: Ready with rxn 1300
Getting enzyme codes: Ready with rxn 1400
Getting enzyme codes: Ready with rxn 1500
Getting enzyme codes: Ready with rxn 1600
Getting enzyme codes: Ready with rxn 1700
Getting enzyme codes: Ready with rxn 1800
Getting enzyme codes: Ready with rxn 1900
Getting enzyme codes: Ready with rxn 1912
Matching kcats: Ready with rxn 10
Matching kcats: Ready with rxn 20
Matching kcats: Ready with rxn 30
Matching kcats: Ready with rxn 40
Matching kcats: Ready with rxn 50
Matching kcats: Ready with rxn 60
Matching kcats: Ready with rxn 70
Matching kcats: Ready with rxn 80
Matching kcats: Ready with rxn 90
Matching kcats: Ready with rxn 100
Matching kcats: Ready with rxn 110
Matching kcats: Ready with rxn 120
Matching kcats: Ready with rxn 130
Matching kcats: Ready with rxn 140
Matching kcats: Ready with rxn 150
Matching kcats: Ready with rxn 160
Matching kcats: Ready with rxn 170
Matching kcats: Ready with rxn 180
Matching kcats: Ready with rxn 190
Matching kcats: Ready with rxn 200
Matching kcats: Ready with rxn 210
Matching kcats: Ready with rxn 220
Matching kcats: Ready with rxn 230
Matching kcats: Ready with rxn 240
Matching kcats: Ready with rxn 250
Matching kcats: Ready with rxn 260
Matching kcats: Ready with rxn 270
Matching kcats: Ready with rxn 280
Matching kcats: Ready with rxn 290
Matching kcats: Ready with rxn 300
Matching kcats: Ready with rxn 310
Matching kcats: Ready with rxn 320
Matching kcats: Ready with rxn 330
Matching kcats: Ready with rxn 340
Matching kcats: Ready with rxn 350
Matching kcats: Ready with rxn 360
Matching kcats: Ready with rxn 370
Matching kcats: Ready with rxn 380
Matching kcats: Ready with rxn 390
Matching kcats: Ready with rxn 400
Matching kcats: Ready with rxn 410
Matching kcats: Ready with rxn 420
Matching kcats: Ready with rxn 430
Matching kcats: Ready with rxn 440
Matching kcats: Ready with rxn 450
Matching kcats: Ready with rxn 460
Matching kcats: Ready with rxn 470
Matching kcats: Ready with rxn 480
Matching kcats: Ready with rxn 490
Matching kcats: Ready with rxn 500
Matching kcats: Ready with rxn 510
Matching kcats: Ready with rxn 520
Matching kcats: Ready with rxn 530
Matching kcats: Ready with rxn 540
Matching kcats: Ready with rxn 550
Matching kcats: Ready with rxn 560
Matching kcats: Ready with rxn 570
Matching kcats: Ready with rxn 580
Matching kcats: Ready with rxn 590
Matching kcats: Ready with rxn 600
Matching kcats: Ready with rxn 610
Matching kcats: Ready with rxn 620
Matching kcats: Ready with rxn 630
Matching kcats: Ready with rxn 640
Matching kcats: Ready with rxn 650
Matching kcats: Ready with rxn 660
Matching kcats: Ready with rxn 670
Matching kcats: Ready with rxn 680
Matching kcats: Ready with rxn 690
Matching kcats: Ready with rxn 700
Matching kcats: Ready with rxn 710
Matching kcats: Ready with rxn 720
Matching kcats: Ready with rxn 730
Matching kcats: Ready with rxn 740
Matching kcats: Ready with rxn 750
Matching kcats: Ready with rxn 760
Matching kcats: Ready with rxn 770
Matching kcats: Ready with rxn 780
Matching kcats: Ready with rxn 790
Matching kcats: Ready with rxn 800
Matching kcats: Ready with rxn 810
Matching kcats: Ready with rxn 820
Matching kcats: Ready with rxn 830
Matching kcats: Ready with rxn 840
Matching kcats: Ready with rxn 850
Matching kcats: Ready with rxn 860
Matching kcats: Ready with rxn 870
Matching kcats: Ready with rxn 880
Matching kcats: Ready with rxn 890
Matching kcats: Ready with rxn 900
Matching kcats: Ready with rxn 910
Matching kcats: Ready with rxn 920
Matching kcats: Ready with rxn 930
Matching kcats: Ready with rxn 940
Matching kcats: Ready with rxn 950
Matching kcats: Ready with rxn 960
Matching kcats: Ready with rxn 970
Matching kcats: Ready with rxn 980
Matching kcats: Ready with rxn 990
Matching kcats: Ready with rxn 1000
Matching kcats: Ready with rxn 1010
Matching kcats: Ready with rxn 1020
Matching kcats: Ready with rxn 1030
Matching kcats: Ready with rxn 1040
Matching kcats: Ready with rxn 1050
Matching kcats: Ready with rxn 1060
Matching kcats: Ready with rxn 1070
Matching kcats: Ready with rxn 1080
Matching kcats: Ready with rxn 1090
Matching kcats: Ready with rxn 1100
Matching kcats: Ready with rxn 1110
Matching kcats: Ready with rxn 1120
Matching kcats: Ready with rxn 1130
Matching kcats: Ready with rxn 1140
Matching kcats: Ready with rxn 1150
Matching kcats: Ready with rxn 1160
Matching kcats: Ready with rxn 1170
Matching kcats: Ready with rxn 1180
Matching kcats: Ready with rxn 1190
Matching kcats: Ready with rxn 1200
Matching kcats: Ready with rxn 1210
Matching kcats: Ready with rxn 1220
Matching kcats: Ready with rxn 1230
Matching kcats: Ready with rxn 1240
Matching kcats: Ready with rxn 1250
Matching kcats: Ready with rxn 1260
Matching kcats: Ready with rxn 1270
Matching kcats: Ready with rxn 1280
Matching kcats: Ready with rxn 1290
Matching kcats: Ready with rxn 1300
Matching kcats: Ready with rxn 1310
Matching kcats: Ready with rxn 1320
Matching kcats: Ready with rxn 1330
Matching kcats: Ready with rxn 1340
Matching kcats: Ready with rxn 1350
Matching kcats: Ready with rxn 1360
Matching kcats: Ready with rxn 1370
Matching kcats: Ready with rxn 1380
Matching kcats: Ready with rxn 1390
Matching kcats: Ready with rxn 1400
Matching kcats: Ready with rxn 1410
Matching kcats: Ready with rxn 1420
Matching kcats: Ready with rxn 1430
Matching kcats: Ready with rxn 1440
Matching kcats: Ready with rxn 1450
Matching kcats: Ready with rxn 1460
Matching kcats: Ready with rxn 1470
Matching kcats: Ready with rxn 1480
Matching kcats: Ready with rxn 1490
Matching kcats: Ready with rxn 1500
Matching kcats: Ready with rxn 1510
Matching kcats: Ready with rxn 1520
Matching kcats: Ready with rxn 1530
Matching kcats: Ready with rxn 1540
Matching kcats: Ready with rxn 1550
Matching kcats: Ready with rxn 1560
Matching kcats: Ready with rxn 1570
Matching kcats: Ready with rxn 1580
Matching kcats: Ready with rxn 1590
Matching kcats: Ready with rxn 1600
Matching kcats: Ready with rxn 1610
Matching kcats: Ready with rxn 1620
Matching kcats: Ready with rxn 1630
Matching kcats: Ready with rxn 1640
Matching kcats: Ready with rxn 1650
Matching kcats: Ready with rxn 1660
Matching kcats: Ready with rxn 1670
Matching kcats: Ready with rxn 1680
Matching kcats: Ready with rxn 1690
Matching kcats: Ready with rxn 1700
Matching kcats: Ready with rxn 1710
Matching kcats: Ready with rxn 1720
Matching kcats: Ready with rxn 1730
Matching kcats: Ready with rxn 1740
Matching kcats: Ready with rxn 1750
Matching kcats: Ready with rxn 1760
Matching kcats: Ready with rxn 1770
Matching kcats: Ready with rxn 1780
Matching kcats: Ready with rxn 1790
Matching kcats: Ready with rxn 1800
Matching kcats: Ready with rxn 1810
Matching kcats: Ready with rxn 1820
Matching kcats: Ready with rxn 1830
Matching kcats: Ready with rxn 1840
Matching kcats: Ready with rxn 1850
Matching kcats: Ready with rxn 1860
Matching kcats: Ready with rxn 1870
Matching kcats: Ready with rxn 1880
Matching kcats: Ready with rxn 1890
Matching kcats: Ready with rxn 1900
Matching kcats: Ready with rxn 1910
Matching kcats: Ready with rxn 1912
Adding enzymes to rxns: Ready with rxn 100
Adding enzymes to rxns: Ready with rxn 200
Adding enzymes to rxns: Ready with rxn 300
Adding enzymes to rxns: Ready with rxn 400
Adding enzymes to rxns: Ready with rxn 500
Adding enzymes to rxns: Ready with rxn 600
Adding enzymes to rxns: Ready with rxn 700
Adding enzymes to rxns: Ready with rxn 800
Adding enzymes to rxns: Ready with rxn 900
Adding enzymes to rxns: Ready with rxn 1000
Adding enzymes to rxns: Ready with rxn 1100
Adding enzymes to rxns: Ready with rxn 1200
Adding enzymes to rxns: Ready with rxn 1300
Adding enzymes to rxns: Ready with rxn 1400
Adding enzymes to rxns: Ready with rxn 1500
Adding enzymes to rxns: Ready with rxn 1600
Adding enzymes to rxns: Ready with rxn 1700
Adding enzymes to rxns: Ready with rxn 1800
Adding enzymes to rxns: Ready with rxn 1900
Adding enzymes to rxns: Ready with rxn 2000
Adding enzymes to rxns: Ready with rxn 2100
Adding enzymes to rxns: Ready with rxn 2200
Adding enzymes to rxns: Ready with rxn 2300
Adding enzymes to rxns: Ready with rxn 2400
Adding enzymes to rxns: Ready with rxn 2500
Adding enzymes to rxns: Ready with rxn 2600
Adding enzymes to rxns: Ready with rxn 2700
Adding enzymes to rxns: Ready with rxn 2800
Adding enzymes to rxns: Ready with rxn 2884
Improving model with curated data........................................................... Done!
Removing repeated rxn: r_1341 & r_1342
Removing repeated rxn: r_1349 & r_1350
Removing repeated rxn: r_1360 & r_1361
Removing repeated rxn: r_1362 & r_1457
Removing repeated rxn: r_1372 & r_1373
Removing repeated rxn: r_1383 & r_1384
Removing repeated rxn: r_1522 & r_1523
Removing repeated rxn: r_1524 & r_1525
Removing repeated rxn: r_1535 & r_1536_REV
Removing repeated rxn: r_1538 & r_1539
Removing repeated rxn: r_1543 & r_1542_REV
Removing repeated rxn: r_1545 & r_1546
Removing repeated rxn: r_1555 & r_1553_REV
Removing repeated rxn: r_1578 & r_1579
Removing repeated rxn: r_1582 & r_1583
Removing repeated rxn: r_1591 & r_1592
Removing repeated rxn: r_1593 & r_1594_REV
Removing repeated rxn: r_1594 & r_1595
Removing repeated rxn: r_1602 & r_1603
Removing repeated rxn: r_1609 & r_1607_REV
Removing repeated rxn: r_1620 & r_1619_REV
Removing repeated rxn: r_1628 & r_1629
Removing repeated rxn: r_1640 & r_1641
Removing repeated rxn: r_1647 & r_1648
Removing repeated rxn: r_1649 & r_1650
Removing repeated rxn: r_1654 & r_1655
Removing repeated rxn: r_1670 & r_1669_REV
Removing repeated rxn: r_1672 & r_1674_REV
Removing repeated rxn: r_1674 & r_1675
Removing repeated rxn: r_1682 & r_1683_REV
Removing repeated rxn: r_1683 & r_1684
Removing repeated rxn: r_1690 & r_1691_REV
Removing repeated rxn: r_1691 & r_1692
Removing repeated rxn: r_1713 & r_1714_REV
Removing repeated rxn: r_1714 & r_1715
Removing repeated rxn: r_1716 & r_1717_REV
Removing repeated rxn: r_1717 & r_1718
prot_abundance file is empty or not available. A default value of f=0.5 is set instead
WARNING: Reaction r_1771 is not present in the reaction list

Matching data to enzymes in model...
Estimating GAM:
Fitted GAM = 53.4 -> Error = 0.31657
[Warning: MATLAB has disabled some advanced graphics rendering features by
switching to software OpenGL. For more information, click <a
href="matlab:opengl('problems')">here</a>.] 
 
Total protein amount measured = 0 g/gDW
Total enzymes measured = 0 enzymes
Enzymes in model with 0 g/gDW = 0 enzymes
Total protein amount not measured = 0.546 g/gDW
Total enzymes not measured = 716 enzymes
Total protein in model = 0.546 g/gDW

***************************************************************
                The ECmodel is overconstrained                 
******************* Limiting Kcats curation *******************
*Iteration #1
 Automatic search // EC#: 1.14.19.41
  Protein:W0TF60 Rxn#:1934 name: 5,7,24(28)-ergostatrienol[r]+NADP(+)[r]=>ergosta-5,7,22,24(28)-tetraen-3beta-ol[r]+H+[r]+NADPH[r] (No1)
  prev_Kcat:0.015 new_Kcat:0.17 CC:0.39894 Err:-20.0879%

*Iteration #2
 Automatic search // EC#: 6.3.5.3
  Protein:W0TBC7 Rxn#:2235 name: 5'-Phosphoribosylformylglycinamide:L-glutamine amido-ligase (ADP-forming) (No1)
  prev_Kcat:0.05 new_Kcat:5.0675 CC:0.26475 Err:1.0688%

***************************************************************
        Fitting the average enzymes saturation factor          
Fitting sigma factor: 0.01   error: 96.9366%
Fitting sigma factor: 0.02   error: 93.5994%
Fitting sigma factor: 0.03   error: 90.2623%
Fitting sigma factor: 0.04   error: 86.9252%
Fitting sigma factor: 0.05   error: 83.5881%
Fitting sigma factor: 0.06   error: 80.251%
Fitting sigma factor: 0.07   error: 76.9138%
Fitting sigma factor: 0.08   error: 73.5767%
Fitting sigma factor: 0.09   error: 70.2396%
Fitting sigma factor: 0.1   error: 66.9025%
Fitting sigma factor: 0.11   error: 63.5653%
Fitting sigma factor: 0.12   error: 60.2282%
Fitting sigma factor: 0.13   error: 56.8911%
Fitting sigma factor: 0.14   error: 53.554%
Fitting sigma factor: 0.15   error: 50.2168%
Fitting sigma factor: 0.16   error: 46.8797%
Fitting sigma factor: 0.17   error: 43.5426%
Fitting sigma factor: 0.18   error: 40.2055%
Fitting sigma factor: 0.19   error: 36.8684%
Fitting sigma factor: 0.2   error: 33.5312%
Fitting sigma factor: 0.21   error: 30.1941%
Fitting sigma factor: 0.22   error: 26.857%
Fitting sigma factor: 0.23   error: 23.5199%
Fitting sigma factor: 0.24   error: 20.1827%
Fitting sigma factor: 0.25   error: 16.8456%
Fitting sigma factor: 0.26   error: 13.5085%
Fitting sigma factor: 0.27   error: 10.1714%
Fitting sigma factor: 0.28   error: 6.8342%
Fitting sigma factor: 0.29   error: 3.4971%
Fitting sigma factor: 0.3   error: 0.16%
Fitting sigma factor: 0.31   error: -1.0687%
Fitting sigma factor: 0.32   error: -1.0687%
Fitting sigma factor: 0.33   error: -1.0687%
Fitting sigma factor: 0.34   error: -1.0687%
Fitting sigma factor: 0.35   error: -1.0687%
Fitting sigma factor: 0.36   error: -1.0687%
Fitting sigma factor: 0.37   error: -1.0687%
Fitting sigma factor: 0.38   error: -1.0687%
Fitting sigma factor: 0.39   error: -1.0687%
Fitting sigma factor: 0.4   error: -1.0687%
Fitting sigma factor: 0.41   error: -1.0687%
Fitting sigma factor: 0.42   error: -1.0687%
Fitting sigma factor: 0.43   error: -1.0687%
Fitting sigma factor: 0.44   error: -1.0687%
Fitting sigma factor: 0.45   error: -1.0687%
Fitting sigma factor: 0.46   error: -1.0687%
Fitting sigma factor: 0.47   error: -1.0687%
Fitting sigma factor: 0.48   error: -1.0687%
Fitting sigma factor: 0.49   error: -1.0687%
Fitting sigma factor: 0.5   error: -1.0687%
Fitting sigma factor: 0.51   error: -1.0687%
Fitting sigma factor: 0.52   error: -1.0687%
Fitting sigma factor: 0.53   error: -1.0687%
Fitting sigma factor: 0.54   error: -1.0687%
Fitting sigma factor: 0.55   error: -1.0687%
Fitting sigma factor: 0.56   error: -1.0687%
Fitting sigma factor: 0.57   error: -1.0687%
Fitting sigma factor: 0.58   error: -1.0687%
Fitting sigma factor: 0.59   error: -1.0687%
Fitting sigma factor: 0.6   error: -1.0687%
Fitting sigma factor: 0.61   error: -1.0687%
Fitting sigma factor: 0.62   error: -1.0687%
Fitting sigma factor: 0.63   error: -1.0687%
Fitting sigma factor: 0.64   error: -1.0687%
Fitting sigma factor: 0.65   error: -1.0687%
Fitting sigma factor: 0.66   error: -1.0687%
Fitting sigma factor: 0.67   error: -1.0687%
Fitting sigma factor: 0.68   error: -1.0687%
Fitting sigma factor: 0.69   error: -1.0687%
Fitting sigma factor: 0.7   error: -1.0687%
Fitting sigma factor: 0.71   error: -1.0687%
Fitting sigma factor: 0.72   error: -1.0687%
Fitting sigma factor: 0.73   error: -1.0687%
Fitting sigma factor: 0.74   error: -1.0687%
Fitting sigma factor: 0.75   error: -1.0687%
Fitting sigma factor: 0.76   error: -1.0687%
Fitting sigma factor: 0.77   error: -1.0687%
Fitting sigma factor: 0.78   error: -1.0687%
Fitting sigma factor: 0.79   error: -1.0687%
Fitting sigma factor: 0.8   error: -1.0687%
Fitting sigma factor: 0.81   error: -1.0687%
Fitting sigma factor: 0.82   error: -1.0687%
Fitting sigma factor: 0.83   error: -1.0687%
Fitting sigma factor: 0.84   error: -1.0687%
Fitting sigma factor: 0.85   error: -1.0687%
Fitting sigma factor: 0.86   error: -1.0687%
Fitting sigma factor: 0.87   error: -1.0687%
Fitting sigma factor: 0.88   error: -1.0687%
Fitting sigma factor: 0.89   error: -1.0687%
Fitting sigma factor: 0.9   error: -1.0687%
Fitting sigma factor: 0.91   error: -1.0687%
Fitting sigma factor: 0.92   error: -1.0687%
Fitting sigma factor: 0.93   error: -1.0687%
Fitting sigma factor: 0.94   error: -1.0687%
Fitting sigma factor: 0.95   error: -1.0687%
Fitting sigma factor: 0.96   error: -1.0687%
Fitting sigma factor: 0.97   error: -1.0687%
Fitting sigma factor: 0.98   error: -1.0687%
Fitting sigma factor: 0.99   error: -1.0687%
Fitting sigma factor: 1   error: -1.0687%
Sigma factor (fitted for growth on glucose): 0.3
Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.
Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.

### CODE REVIEW

**Comment by IVANDOMENZAIN** [comment]
@mihai-sysbio, after some work and weird fixes I realized that the issues with `iSM996` could just be fixed by adding an empty `prot_abundance.txt` file for *K. marxianus* in the `iSM996/scripts` subdirectory. Things look good now and the pipeline returns the expected outputs.

**Comment by IVANDOMENZAIN** [comment]
Should we merge the corresponding changes into `feat/updated-models` through this PR or by creating another PR based on [fix/iSM996](https://github.com/MetabolicAtlas/ecModels/tree/fix/iSM996), in which the changes were initially introduced?

**Comment by mihai-sysbio** [comment]
I would go for [a PR from fix/iSM996](https://github.com/MetabolicAtlas/ecModels/compare/feat/updated-models...MetabolicAtlas:fix/iSM996). However, some of the model specific changes should be reverted (eg in `config.ini`). This would be a good time to also make the model name consisted by changing the `install_dir` to `eciSM996`.

**Comment by IVANDOMENZAIN** [comment]
> I would go for [a PR from fix/iSM996](https://github.com/MetabolicAtlas/ecModels/compare/feat/updated-models...MetabolicAtlas:fix/iSM996). However, some of the model specific changes should be reverted (eg in `config.ini`). This would be a good time to also make the model name consisted by changing the `install_dir` to `eciSM996`.

I agree. I'll take care of this PR then, thanks!

**Comment by mihai-sysbio** [comment]
I'm tempted to close the current PR and obtain fresh models directly in the parent repo `SysBioChalmers/ecModels`. Any thoughts?

**Comment by IVANDOMENZAIN** [comment]
> I'm tempted to close the current PR and obtain fresh models directly in the parent repo `SysBioChalmers/ecModels`. Any thoughts?

@mihai-sysbio  Do you mean to close the PRs open by the automator in this fork in order to merge `feat/updated_models` (from this repo) into its parent `SysBioChalmers/ecModels`?

**Comment by mihai-sysbio** [comment]
Yes. The aim would be to avoid carrying over "new" enzyme constrained models from this fork over to the parent.

**Comment by IVANDOMENZAIN** [comment]
> Yes. The aim would be to avoid carrying over "new" enzyme constrained models from this fork over to the parent.

@mihai-sysbio sounds good to me, should we then merge #73 into `feat/updated_models` here prior to the merge that you're thinking about?

**Pull request closed without merging**
