### PR TITLE
refactor: run automation on any branch except some

### PR DESCRIPTION
**Pull request by mihai-sysbio**
This pull request aim to remove the need to update the automation script for every custom branch. The goal is to have the automation run on any branch except `master`, `main`, or any of the `update/*` branches that get created by the pipeline itself, since that would be an infinite loop.
Another fix was to remove all existing files and folders before the pipeline starts, so that in case of error the files continue to exist in the runner until the next run.

### CODE REVIEW

**Comment by IVANDOMENZAIN** [comment]
Great ideas! I've tested this PR by re-running the jobs again and it passes the cloning step and enters the MATLAB GECKO part, so it seems that everything works well :)

**Review by IVANDOMENZAIN — APPROVED** [review]

**Comment by IVANDOMENZAIN** [comment]
@mihai-sysbio I've seen an error in the automation log when letting the pipeline to run until the end of at least one model, here you have links to both a case with [ecYeastGEM](https://github.com/MetabolicAtlas/ecModels/runs/1747696000?check_suite_focus=true#step:3:1127) and another one with [eciSM996](https://github.com/MetabolicAtlas/ecModels/runs/1749088019?check_suite_focus=true#step:3:391), apparently triggered in the `system.git_add_and_pr` step.

**Comment by mihai-sysbio** [comment]
Ah right. This is because I added a `--depth 1` to the cloning step. Will fix asap.

**Comment by mihai-sysbio** [comment]
Sorry for the delay. [This](https://github.com/MetabolicAtlas/ecModels/commit/a30b3e366a983d8912a8698493fa95f81ca2ca87) should do it, we'll see soon.

**Comment by IVANDOMENZAIN** [comment]
No worries @mihai-sysbio :) let's see how this runs, fingers crossed!

**Comment by mihai-sysbio** [comment]
We can leave the Action to run until the end, but it worked for [`ecYeastGEM`](https://github.com/MetabolicAtlas/ecModels/pull/79)

**Comment by IVANDOMENZAIN** [comment]
@mihai-sysbio , I can see that the Action crashed for the `eciSM996` case, I've tried but I'm having problems displaying the actions log, don't know why. Could you share a screenshot of the error (in case that is MATLAB  or model related)? then I can try to fix it.

**Comment by mihai-sysbio** [comment]
I'm not sure why the Actions log is empty for that run. There was nothing useful in the Matlab crash dumps, nor did I manage to find anything in the action logs. So it seems like the only option is to run this again. Since the job takes such a long time, it might be faster to debug this in the original `ecModels` repo. The new runner for that should be ready. What do you think @IVANDOMENZAIN ?

**Comment by IVANDOMENZAIN** [comment]
Let's proceed @mihai-sysbio! but let's merge this into a `devel` branch in the original `ecModels` repo

**Pull request merged**
