### PR TITLE
update eciSM966 based on v1.0.0

### PR DESCRIPTION
**Pull request by automator-metatlas**
MATLAB is selecting SOFTWARE OPENGL rendering.

                            < M A T L A B (R) >
                  Copyright 1984-2018 The MathWorks, Inc.
                   R2018b (9.5.0.944444) 64-bit (glnxa64)
                              August 28, 2018

 
To get started, type doc.
For product information, visit www.mathworks.com.
 

      _____   _____   _____   _____     _____     |
     /  ___| /  _  \ |  _  \ |  _  \   / ___ \    |   COnstraint-Based Reconstruction and Analysis
     | |     | | | | | |_| | | |_| |  | |___| |   |   The COBRA Toolbox - 2021
     | |     | | | | |  _  { |  _  /  |  ___  |   |
     | |___  | |_| | | |_| | | | \ \  | |   | |   |   Documentation:
     \_____| \_____/ |_____/ |_|  \_\ |_|   |_|   |   http://opencobra.github.io/cobratoolbox
                                                  | 

 > Checking if git is installed ...  Done (version: 1.8.3.).
 > Checking if the repository is tracked using git ...  Done.
 > Checking if curl is installed ...  Done.
 > Checking if remote can be reached ...  Done.
 > Initializing and updating submodules (this may take a while)... Done.
 > Adding all the files of The COBRA Toolbox ...  Done.
 > Define CB map output... set to svg.
 > TranslateSBML is installed and working properly.
 > Configuring solver environment variables ...
   - [----] ILOG_CPLEX_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   - [----] GUROBI_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   - [----] TOMLAB_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   - [----] MOSEK_PATH: --> set this path manually after installing the solver ( see https://opencobra.github.io/cobratoolbox/docs/solvers.html )
   Done.
 > Checking available solvers and solver interfaces ... Done.
 > Setting default solvers ... Done.
 > Saving the MATLAB path ... Done.
   - The MATLAB path was saved as ~/pathdef.m.

 > Summary of available solvers and solver interfaces

			Support 	   LP 	 MILP 	   QP 	 MIQP 	  NLP
	----------------------------------------------------------------------
	gurobi       	active        	    1 	    1 	    1 	    1 	    -
	ibm_cplex    	active        	    0 	    0 	    0 	    0 	    -
	tomlab_cplex 	active        	    0 	    0 	    0 	    0 	    -
	glpk         	active        	    1 	    1 	    - 	    - 	    -
	mosek        	active        	    0 	    - 	    0 	    - 	    -
	matlab       	active        	    0 	    - 	    - 	    - 	    0
	pdco         	active        	    1 	    - 	    1 	    - 	    -
	quadMinos    	active        	    1 	    - 	    - 	    - 	    -
	dqqMinos     	active        	    1 	    - 	    1 	    - 	    -
	cplex_direct 	active        	    0 	    0 	    0 	    - 	    -
	cplexlp      	active        	    0 	    - 	    - 	    - 	    -
	qpng         	passive       	    - 	    - 	    1 	    - 	    -
	tomlab_snopt 	passive       	    - 	    - 	    - 	    - 	    0
	lp_solve     	legacy        	    1 	    - 	    - 	    - 	    -
	----------------------------------------------------------------------
	Total        	-             	    6 	    2 	    4 	    1 	    0

 + Legend: - = not applicable, 0 = solver not compatible or not installed, 1 = solver installed.

 > You can solve LP problems using: 'gurobi' - 'glpk' - 'pdco' - 'quadMinos' 
 > You can solve MILP problems using: 'gurobi' - 'glpk' 
 > You can solve QP problems using: 'gurobi' - 'pdco' 
 > You can solve MIQP problems using: 'gurobi' 
 > You can solve NLP problems using: 

 > Checking for available updates ...
> You cannot update your fork using updateCobraToolbox() because this is a development branch.
> The current branch is: detached HEAD
> The last commit to the current branch is: 6c49aa
> You can use MATLAB.devTools (https://github.com/opencobra/MATLAB.devTools) to update your fork.
Converting COBRA structure to RAVEN..

***************************************************************
   GECKO: Adding enzyme constraints to a genome-scale model
***************************************************************

Getting genome-scale model ready... Done!

==================
Generating ecModel:
==================
Retrieving EC numbers....................... Done!
Matching kcats....................... Done!
Adding enzymes to reactions................................ Done!
Improving model with curated data........................................................... Done!
Removing repeated rxn: r_1341 & r_1342
Removing repeated rxn: r_1349 & r_1350
Removing repeated rxn: r_1360 & r_1361
Removing repeated rxn: r_1362 & r_1457
Removing repeated rxn: r_1372 & r_1373
Removing repeated rxn: r_1383 & r_1384
Removing repeated rxn: r_1522 & r_1523
Removing repeated rxn: r_1524 & r_1525
Removing repeated rxn: r_1535 & r_1536_REV
Removing repeated rxn: r_1538 & r_1539
Removing repeated rxn: r_1543 & r_1542_REV
Removing repeated rxn: r_1545 & r_1546
Removing repeated rxn: r_1555 & r_1553_REV
Removing repeated rxn: r_1578 & r_1579
Removing repeated rxn: r_1582 & r_1583
Removing repeated rxn: r_1591 & r_1592
Removing repeated rxn: r_1593 & r_1594_REV
Removing repeated rxn: r_1594 & r_1595
Removing repeated rxn: r_1602 & r_1603
Removing repeated rxn: r_1609 & r_1607_REV
Removing repeated rxn: r_1620 & r_1619_REV
Removing repeated rxn: r_1628 & r_1629
Removing repeated rxn: r_1640 & r_1641
Removing repeated rxn: r_1647 & r_1648
Removing repeated rxn: r_1649 & r_1650
Removing repeated rxn: r_1654 & r_1655
Removing repeated rxn: r_1670 & r_1669_REV
Removing repeated rxn: r_1672 & r_1674_REV
Removing repeated rxn: r_1674 & r_1675
Removing repeated rxn: r_1682 & r_1683_REV
Removing repeated rxn: r_1683 & r_1684
Removing repeated rxn: r_1690 & r_1691_REV
Removing repeated rxn: r_1691 & r_1692
Removing repeated rxn: r_1713 & r_1714_REV
Removing repeated rxn: r_1714 & r_1715
Removing repeated rxn: r_1716 & r_1717_REV
Removing repeated rxn: r_1717 & r_1718

==============================================================
Generating ecModel with shared pool assumption (ecModel_batch):
==============================================================
prot_abundance file is empty or not available. A default value of f=0.5 is set instead
WARNING: Reaction r_1771 is not present in the reaction list

Matching data to enzymes in model... Done!
Estimating GAM.............................................................. Done!
Fitted GAM = 53.4 -> Error = 0.31657
[Warning: MATLAB has disabled some advanced graphics rendering features by
switching to software OpenGL. For more information, click <a
href="matlab:opengl('problems')">here</a>.] 
Total protein amount measured = 0 g/gDW
Total enzymes measured = 0 enzymes
Enzymes in model with 0 g/gDW = 0 enzymes
Total protein amount not measured = 0.546 g/gDW
Total enzymes not measured = 716 enzymes
Total protein in model = 0.546 g/gDW
The ECmodel is overconstrained!
******************* Limiting Kcats curation *******************
*Iteration #1
 Automatic search // EC#: 1.14.19.41
  Protein:W0TF60 Rxn#:1934 name: 5,7,24(28)-ergostatrienol[r]+NADP(+)[r]=>ergosta-5,7,22,24(28)-tetraen-3beta-ol[r]+H+[r]+NADPH[r] (No1)
  prev_Kcat:0.015 new_Kcat:0.17 CC:0.39894 Err:-20.0879%
*Iteration #2
 Automatic search // EC#: 6.3.5.3
  Protein:W0TBC7 Rxn#:2235 name: 5'-Phosphoribosylformylglycinamide:L-glutamine amido-ligase (ADP-forming) (No1)
  prev_Kcat:0.05 new_Kcat:5.0675 CC:0.26475 Err:1.0688%
***************************************************************
Fitting sigma factor....................... Done!
Saving simulation results files...
File successfully saved.
Sigma factor (fitted for growth on glucose): 0.3

=============
Saving models:
=============
Saving eciSM966v1.0.0:
Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.
Saving eciSM966_batchv1.0.0:
Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.

### CODE REVIEW

**Comment by IVANDOMENZAIN** [comment]
@mihai-sysbio I just isolated the `iSM996` case in order to assess the fail in this [run](https://github.com/MetabolicAtlas/ecModels/runs/1778257779?check_suite_focus=true). In that occasion the pipeline was running for +12 hrs. and created successful PRs for [yeastGEM](https://github.com/MetabolicAtlas/ecModels/pull/79), [humanGEM](https://github.com/MetabolicAtlas/ecModels/pull/80) and [iYali](https://github.com/MetabolicAtlas/ecModels/pull/81), but not for `iSM996`. Now for this specific case (with no additional changes other than the isolation of the GEM in the config script) the pipeline is able to finish and generate a successful PR. Probably the previously observed failure is related to limitations of the pipeline or even the virtual machine used then? Anyways, I'm writing this just to document the current state of things.

**Comment by mihai-sysbio** [comment]
Thanks for documenting this. Since it's not possible to retrieve the logs for this run and it also takes so long to run, I'm proposing to look at this again in the main repository that uses a faster runner.

**Comment by IVANDOMENZAIN** [comment]
> Thanks for documenting this. Since it's not possible to retrieve the logs for this run and it also takes so long to run, I'm proposing to look at this again in the main repository that uses a faster runner.

You're welcome! Some good news, we got a successful run today for `YeastGEM`, `iYali`, `iSM996` and `humanGEM`. You can check the log [here](https://github.com/MetabolicAtlas/ecModels/runs/1867237609?check_suite_focus=true), it generated PRs for all of them. Now I replicated the `feat/iml` PR in the forked repo and, currently, a run including also `iML1515` (which  works individually) is [active](https://github.com/MetabolicAtlas/ecModels/actions/runs/555971016)

**Comment by mihai-sysbio** [comment]
I've got some good news too: the [new runner is having a go at its first pipeline run](https://github.com/SysBioChalmers/ecModels/runs/1875696412?check_suite_focus=true). If all works well, then any new work can be merged into `SysBioChalmers/ecModels/update_all_models`.

**Pull request closed without merging**
